# 파이썬 기반의 통계 분석

## 강봉주
## 2019-2020 겨울 계절 학기
## 기초 수학: 벡터와 행렬
## bonjour.kang@gmail.com

In [ ]:
# 필요한 패키지
import numpy as np
import scipy
from scipy import linalg as la
import matplotlib.pyplot as plt

# 버전 확인
print(np.__version__)
# 1.15.4
print(scipy.__version__)
# 1.2.1

In [ ]:
# 벡터의 생성
v = np.array([0.61, 0.93, 0.24, 0.27])

print(type(v))
print(v)

In [ ]:
# 벡터의 원소
v = np.array([0.61, 0.93, 0.24, 0.27])
v[0]

In [ ]:
# 벡터의 크기
v = np.array([0.61, 0.93, 0.24, 0.27])
v.shape

In [ ]:
# 부분 벡터의 생성
v = np.array([0.61, 0.93, 0.24, 0.27])
v_sub = v[0:2]
print(v_sub)

## 특별한 벡터

In [ ]:
# 영 벡터
zeros = np.zeros(shape=(4,))
print(zeros)

In [ ]:
# 1 벡터
size = 3
one = np.ones(shape=(size, ))
print(one)

In [ ]:
# 단위 벡터
size = 3
e = np.diag(np.ones(shape=(size,)))
print(e)

# 하나의 단위  벡터의 예
print('하나의 단위벡터:', e[:,1])

## 벡터의 연산

In [ ]:
# 벡터의 덧셈
a = np.array([1, 3])
b = np.array([3, 1])

print(a+b)

# 교환 법칙
print('교환:', a + b == b + a)

# 결합 법칙
d = np.array([1, 2])
print('결합', (a + b) + d == a + (b + d))

In [ ]:
# 벡터의 뺄셈
a = np.array([3, 1])
b = np.array([1, 3])

print(b-a)

In [ ]:
# 스칼라-벡터 곱
alpha = 1/2
a = np.array([2, 3])
print(alpha * a)

# 교환 법칙
alpha = 0.5
a = np.array([2, 3])
alpha * a == a * alpha
# array([ True,  True])

# 분배 법칙
beta = 0.7
(alpha + beta) * a == alpha * a +beta * a
# array([ True,  True])

In [ ]:
# 선형 결합
beta = np.array([0.7, 0.9])
a = np.array([1, 3])
b = np.array([3, 1])
a_shrink = beta[0] * a
b_shrink = beta[1] * b

d = a_shrink + b_shrink
print(d)


## 내적

In [ ]:
# 내적 계산
a = np.array([-1, 2, 3])
b = np.array([1, -2, 4])

print(np.sum(a*b))

np.inner(a, b) == np.dot(a, b)

In [ ]:
# 내적의 성질
a = np.array([-1, 2, 3])
b = np.array([1, -2, 4])

# 교환 법칙
print(np.dot(a, b) == np.dot(b, a))

# 결합 법칙
alpha= 0.5
print(np.dot(alpha * a, b) == alpha * np.dot(a, b))

# 분배 법칙
c = np.array([1, 2, 3])
np.dot(a+b, c) == np.dot(a,c) + np.dot(b, c)

In [ ]:
# 내적의 활용

a = np.array([1, 2, 3])
size = len(a)
ones = np.ones(shape=(size,))

# 합의 표현
print(np.dot(ones, a) == np.sum(a))

# 평균의 표현
print(np.dot(ones, a) / len(a) == np.mean(a))

# 제곱합의 표현
print(np.dot(a, a) == np.sum(np.square(a)))

## 벡터 노름

In [ ]:
# 필요한 패키지
from scipy import linalg as la

# 벡터 노름의 계산
a = np.array([-1, 2, 3])
print("%.3f" %la.norm(a))

la.norm(a) == np.sqrt(np.dot(a, a))

In [ ]:
# 벡터 노름의 성질
a = np.array([-1, 2, 3])
b = np.array([1, -2, 4])

# 스칼라 곱
beta = 0.5
print(la.norm(beta * a) == np.abs(beta) * la.norm(a))

# 삼각형의 한 변의 길이는 다른 두변의 길이의 합보다 작다
print(la.norm(a + b) <= la.norm(a) + la.norm(b))

# 길이는 0보다 크거나 작다
print(la.norm(a) >= 0 )

## 내적과 노름

In [ ]:
# 직교정규 벡터 확인
a1 = 1/np.sqrt(2) * np.array([-1, 1])
a2 = 1/np.sqrt(2) * np.array([1, 1])

print(la.norm(a1))
print(la.norm(a2))
print(np.dot(a1, a2))

# 행렬

## 행렬 표현

In [ ]:
# 정의: 2차원 배열
A = np.array(np.random.RandomState(123).normal(size=16)).reshape(4, 4)
print(np.round(A, 2))

In [ ]:
# 행렬의 크기
A = np.random.RandomState(123).randint(1, 12, size=12).reshape(3, 4)
print(A)
print(A.shape)

In [ ]:
# 행렬의 표기법
A = np.random.RandomState(123).randint(1, 12, size=12).reshape(3, 4)
print(A)
print('[1, 1] 원소', A[0, 0])

## 행렬 연산

In [ ]:
# 행렬 덧셈
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(3, 9).reshape(2, 3)

print(A)
print(B)
print(A+B)

In [ ]:
# 행렬 덧셈의 성질
# 교환 법칙
A + B == B + A

In [ ]:
# 스칼라와 행렬 곱: *
c = 0.1
print(c * A)

print(c*A == A*c)

In [ ]:
# 행렬의 전치
A = np.arange(1, 7).reshape(3, 2)
print(A)

A_transpose = A.T
print(A_transpose)

In [ ]:
# 행렬 전치의 성질
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(3, 9).reshape(2, 3)

print(A)
print(B)

print((A + B).T)
print(A.T + B.T)

c = 0.1
print((c*A).T == c*A.T)

In [ ]:
# 행렬 곱
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(1, 7).reshape(3, 2)

print(A)
print(B)

print(A.shape)
print(B.shape)

In [ ]:
# 행렬곱 연산자: @
np.matmul(A, B) == A @ B
print(A @ B)

# 행렬곱 계산 방식
C = A @ B
print(C[1, 0] == np.dot(A[1,:], B[:,0]))
# True

In [ ]:
# 행렬곱의 성질
A = np.arange(1, 5).reshape(2, 2)
B = np.arange(5, 9).reshape(2, 2)

print(A)
# [[1 2]
#  [3 4]]
print(B)
# [[5 6]
#  [7 8]]

A @ B == B @ A
# array([[False, False],
#        [False, False]])

In [ ]:
# 부분 행렬
A = np.arange(1, 13).reshape(4, 3)
print(A)

# 유형 1
print(A[0:2, 1:3])

# 유형 2
print(A[:, 1:3])

# 유형 3
print(A[[0, 2], :][:, [1, 2]])

## 특별한 행렬

In [ ]:
#  영 행렬
size = 3
np.zeros(shape=(size, size))

In [ ]:
# 항등 행렬
np.identity(n=size)

In [ ]:
# 대각 행렬
np.diag([1, 2, 3])

In [ ]:
# 상삼각 행렬
np.triu([[1,2,3],[1, 2, 7],[7,8,5]], k=0)

In [ ]:
# 직교 행렬(orthogonal matrix)
A = np.array([[1,0], [0, -1]])
print(A)
print(A.T @ A)
print(A @ A.T)